app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"    

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#BladeTesterCalendarBundle:
#    resource: "@BladeTesterCalendarBundle/Resources/config/routing.yml"
#    prefix:   /