# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:


    app.form.registration:
            class: AppBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }
    app.form.profile:
            class: AppBundle\Form\ProfileType
            tags:
                - { name: form.type, alias: app_user_profile }

    app_user.registration_listener:
      class: AppBundle\EventListener\RegistrationListener
      arguments: []
      tags:
        - { name: kernel.event_subscriber }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.calendar_listener:
        class: AppBundle\EventListener\CalendarEventListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }


    sonata.admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [~, AppBundle\Entity\Event, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Clientèle, label: Rendez-vous }
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Clientèle, label: Clients }
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.employe:
        class: AppBundle\Admin\EmployeAdmin
        arguments: [~, AppBundle\Entity\Employe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Employé, label: Employé }
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Usagé, label: Usagé }
        calls:
            - [ setTranslationDomain, [AppBundle]]